-dontwarn com.tomtom.sdk.navigation.routeprojection.common.infrastructure.MapperKt
-keepnames class **
-keep class com.tomtom.** { *; }
-keep interface com.tomtom.** { *; }
-keep enum com.tomtom.** { *; }
-keep class org.xmlpull.** { *; }
